name: HeadDatabaseWall
main: me.blvckbytes.head_database_wall.HeadDatabaseWallPlugin
version: 0.1
author: BlvckBytes
api-version: 1.21
depends: [HeadDatabase]
commands:
  headdatabasewall:
    aliases: [hdbw]